"""Hindsight's declared config surface — rendered by the generic desktop panel."""

from plugins.memory.config_schema import (
    KIND_SECRET,
    KIND_SELECT,
    KIND_TEXT,
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hindsight",
    label="Hindsight",
    fields=(
        ProviderField(
            key="mode",
            label="Mode",
            kind=KIND_SELECT,
            default="cloud",
            description="How Hermes connects to Hindsight.",
            options=(
                ProviderFieldOption(
                    "cloud",
                    "Cloud",
                    "Hindsight Cloud API (lightweight, just needs an API key)",
                ),
                ProviderFieldOption(
                    "local_external",
                    "Local External",
                    "Connect to an existing Hindsight instance",
                ),
                ProviderFieldOption(
                    "local_embedded",
                    "Local Embedded",
                    "Run Hindsight locally (downloads ~200MB, needs LLM key)",
                ),
            ),
            inline=True,
        ),
        ProviderField(
            key="api_key",
            label="API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="Used to authenticate with the Hindsight API.",
            placeholder="Enter Hindsight API key",
            when=(("mode", "cloud|local_external"),),
            inline=True,
        ),
        ProviderField(
            key="api_url",
            label="API URL",
            kind=KIND_TEXT,
            default="https://api.hindsight.vectorize.io",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            when=(("mode", "cloud|local_external"),),
            inline=True,
        ),
        ProviderField(
            key="llm_provider",
            label="Embedded LLM provider",
            kind=KIND_SELECT,
            default="openai",
            description="LLM provider used for Hindsight extraction, observations, and embeddings in local mode.",
            options=(
                ProviderFieldOption(
                    "openai",
                    "OpenAI-compatible",
                    "Use Hindsight's configured embedded provider.",
                ),
                ProviderFieldOption("anthropic", "Anthropic"),
                ProviderFieldOption("gemini", "Gemini"),
                ProviderFieldOption("groq", "Groq"),
                ProviderFieldOption("openrouter", "OpenRouter"),
                ProviderFieldOption("minimax", "MiniMax"),
                ProviderFieldOption("ollama", "Ollama"),
                ProviderFieldOption("lmstudio", "LM Studio"),
                ProviderFieldOption("openai_compatible", "OpenAI-compatible custom endpoint"),
            ),
            when=(("mode", "local_embedded"),),
            group="Embedded mode",
            inline=True,
        ),
        ProviderField(
            key="llm_base_url",
            label="Embedded LLM base URL",
            kind=KIND_TEXT,
            description="Custom OpenAI-compatible endpoint; used with openai_compatible or openrouter.",
            when=(("mode", "local_embedded"), ("llm_provider", "openai_compatible|openrouter")),
            group="Embedded mode",
            inline=True,
        ),
        ProviderField(
            key="llm_api_key",
            label="Embedded LLM API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_LLM_API_KEY",
            description="Credential for the embedded LLM provider.",
            placeholder="Enter embedded LLM API key",
            when=(("mode", "local_embedded"), ("llm_provider", "openai|anthropic|gemini|groq|openrouter|minimax|ollama|lmstudio|openai_compatible")),
            group="Embedded mode",
            inline=True,
        ),
        ProviderField(
            key="llm_model",
            label="Embedded LLM model",
            kind=KIND_TEXT,
            default="gpt-4o-mini",
            description="Model used by the embedded LLM provider.",
            when=(("mode", "local_embedded"),),
            group="Embedded mode",
            inline=True,
        ),
        ProviderField(
            key="bank_id",
            label="Bank ID",
            kind=KIND_TEXT,
            default="hermes",
            aliases=("bankId",),
            inline=True,
        ),
        ProviderField(
            key="recall_budget",
            label="Recall budget",
            kind=KIND_SELECT,
            default="mid",
            aliases=("budget",),
            options=(
                ProviderFieldOption("low", "low"),
                ProviderFieldOption("mid", "mid"),
                ProviderFieldOption("high", "high"),
            ),
            inline=True,
        ),
    ),
)
